### ISSUE TITLE
Cross compile to ARM 32 bits

### ISSUE THREAD

**Issue by wuruoyu** [tum-ei-eda/utvm_staticrt_codegen#12]
Hi, I am wondering if this tool support cross-compilation (to ARM 32 bits). IMHO, micro-TVM is for embedded systems, and naturally, the AOT compilation should support ARM. 

I see the commented code here:
https://github.com/tum-ei-eda/utvm_staticrt_codegen/blob/6d4c8d98e8826da9c525a7b3f5d8b8ea4e4e1a00/examples/utvm_gen_graph_and_params.py#L118-L128

But I am not sure if it works well and how to make it work. 

Very appreciate your help!

**Comment by PhilippvK** [comment]
We currently do not use microTVM at all to compile the generated kernel sources as we are just interested in the artifacts of the codegen which can essentially be supplied as C-files to any MCU toolchain similar to the CMake configuration for x86 which can be found [here](https://github.com/tum-ei-eda/utvm_staticrt_codegen/blob/master/examples/target_src/CMakeLists.txt).

AFAIK is the `Compiler`/`Flasher` interface mentioned in https://github.com/tum-ei-eda/utvm_staticrt_codegen/blob/1b296f1efcc28671ee21ccbe86a81b968db8b1e5/examples/utvm_gen_graph_and_params.py#L118 being replaced by the [microTVM Project API](https://github.com/apache/tvm/commit/a7297870c0fd58fb834302d8da055d3ba32bf343)

**Comment by PhilippvK** [comment]
Also keep in mind that current neither the Graph Executor nor the AoT executor ist currently used in the `target_src` as it is just there to demonstrate and test the `utvm_staticrt_codegen` which is similar to the AoT compiler but implemented in a different way.

I might be able to update the examples in the repository to optionally use the Graph Executor or AoT compiler in the near future so stay tuned.

**Comment by wuruoyu** [comment]
Thank you for sharing! Please forgive me that I am very new to TVM. 

By any chance, do you know any working AoT compiler examples in microTVM? I want to do an experiment with the microTVM AoT compiler. I know it is still undergoing heavy development but I only need several demo cases of AoT. If you happen to know one, please drop me a pointer. Really appreciate your help!

**Comment by PhilippvK** [comment]
@wuruoyu The best reference I know are actually the `pytest` files used in TVM to test the full AoT flow.

They can be found in [`tvm/tests/python/relay/aot`](https://github.com/apache/tvm/tree/main/tests/python/relay/aot) and invoked via:

```
cd tvm # or whereever you have cloned and build tvm before
export PYTHONPATH=$(pwd)/python
python3 -m pytest tests/python/relay/aot/test_crt_aot.py
```

However as this takes  quite long and does not actually show whats going on under the hood, you are probably better of looking at the [`pytest tests/python/relay/aot/aot_test_utils.py`](https://github.com/apache/tvm/blob/main/tests/python/relay/aot/aot_test_utils.py) helper script used by the scripts to generate AoT projects as well as the used Makefile: [`pytest tests/python/relay/aot/default.mk`](https://github.com/apache/tvm/blob/main/tests/python/relay/aot/default.mk)

**Comment by wuruoyu** [comment]
Thanks a lot! They do look promising!

**Comment by wuruoyu** [comment]
Sorry for bothering you again...

I am wondering if you have tried running ```pytest tests/python/relay/aot/default.mk``` and ```python -m pytest tests/python/relay/aot/test_crt_aot.py```. I install TVM as https://tvm.apache.org/docs/install/from_source.html and invoke the cmd within python virtualenv. However, I see the following error message (it's a toggle list):

<details><summary>Check failed: (reg != nullptr) is false: AttributeError: Operator dyn.expand_dims is not registered</summary>
<p>

```
❯ python -m pytest tests/python/relay/aot/test_crt_aot.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1070, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 500, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 508, in _try_load_conftest
    self._getconftestmodules(anchor, importmode)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 536, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 587, in _importconftest
    self.consider_conftest(mod)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 663, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 443, in register
    self.consider_module(plugin)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 669, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 676, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/home/ruoyu/.virtualenvs/tvm/lib/python3.8/site-packages/_pytest/config/__init__.py", line 703, in import_plugin
    __import__(importspec)
  File "/home/ruoyu/lib/tvm/python/tvm/testing/__init__.py", line 21, in <module>
    from .utils import *
  File "/home/ruoyu/lib/tvm/python/tvm/testing/utils.py", line 84, in <module>
    from tvm.relay.op.contrib.ethosn import ethosn_available
  File "/home/ruoyu/lib/tvm/python/tvm/relay/__init__.py", line 29, in <module>
    from . import prelude
  File "/home/ruoyu/lib/tvm/python/tvm/relay/prelude.py", line 21, in <module>
    from tvm.relay.transform import ToANormalFormExpr
  File "/home/ruoyu/lib/tvm/python/tvm/relay/transform/__init__.py", line 22, in <module>
    from . import fake_quantization_to_integer, mixed_precision
  File "/home/ruoyu/lib/tvm/python/tvm/relay/transform/fake_quantization_to_integer.py", line 22, in <module>
    from ..op import register_fake_quantization_to_integer
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/__init__.py", line 37, in <module>
    from .reduce import *
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/reduce.py", line 22, in <module>
    from .tensor import exp, log, sqrt
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/tensor.py", line 24, in <module>
    from .dyn import _make as _dyn_make
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/dyn/__init__.py", line 21, in <module>
    from . import _transform
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/dyn/_transform.py", line 28, in <module>
    _reg.register_injective_schedule("dyn.expand_dims")
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/op.py", line 279, in register_injective_schedule
    return register_schedule(op_name, _schedule_injective, level)
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/op.py", line 264, in register_schedule
    fstrategy = _create_fstrategy_from_schedule(op_name, schedule)
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/op.py", line 194, in _create_fstrategy_from_schedule
    compute = get(op_name).get_attr("FTVMCompute")
  File "/home/ruoyu/lib/tvm/python/tvm/relay/op/op.py", line 42, in get
    return tvm.ir.Op.get(op_name)
  File "/home/ruoyu/lib/tvm/python/tvm/ir/op.py", line 45, in get
    return _ffi_api.GetOp(op_name)
  File "/home/ruoyu/lib/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  2: TVMFuncCall
  1: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::Op (tvm::runtime::String)>::AssignTypedLambda<tvm::$_1>(tvm::$_1, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  0: tvm::Op::Get(tvm::runtime::String const&)
  File "/home/ruoyu/lib/tvm/src/ir/op.cc", line 46
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (reg != nullptr) is false: AttributeError: Operator dyn.expand_dims is not registered

```

</p>
</details>

I have searched on Github issues and the TVM forum, but find no fix. I am just checking if you have seen these errors and have a fix (or I did something wrong). It would be also great if these ```pytest``` works for a specific version of TVM. If not, I will post an issue on the TVM forum. 

This might be a stupid question and thank you in advance!

**Comment by wuruoyu** [comment]
Sorry I found out that my TVM installation does not work well, so I deleted

**Comment by PhilippvK** [comment]
@wuruoyu I think it had something to do with you TVM files being newer as the ones used to build TVM via CMake as the feature which was resulting in the error was justadded about 8 hours ago.

**Comment by wuruoyu** [comment]
@PhilippvK Exactly, thank you~

By the way, are you able to just run ```pytest tests/python/relay/aot/default.mk```? Or it is just suggesting to me to look at that makefile? 

I tried to run ```pytest tests/python/relay/aot/aot_test_utils.py``` but it shows ```no tests ran```. And when I tried to run ```pytest tests/python/relay/aot/default.mk```, it is complaining that the file is not found.

**Comment by PhilippvK** [comment]
@wuruoyu You should only run `python3 -m pytest tests/python/relay/aot/test_crt_aot.py`. The other files are used by that script but not actually pytests.

**Comment by wuruoyu** [comment]
Thanks a lot! 

With the script in pytests, I am able to compile a mobilenet model binary in X86. Do you know how to use those scripts to cross-compile a binary in Arm? I tried adding some flags but fail... Very appreciate your help!

**Comment by wuruoyu** [comment]
Thanks for all the guidance you gave! I finally am able to do cross-compiling by looking into ```tests/micro/zephyr/test_zephyr_aot.py```. Really appreciate your help!
